name: Generate documentation
on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3
      - name: Clone wiki
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: .wiki
      - name: Parse and generate documentation
        uses: p3lim/lua-doc-parser@v2
        with:
          output: .wiki
      - name: Commit wiki files
        working-directory: .wiki
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if ! [[ -z $(git status -s) ]]; then
            git commit -m "chore: Adding new version of wiki" .
          fi
          git push
